services:
  app:
    build:
      context: .
    ports:
      - 80:80
      - 5173:5173
    networks:
      - net
    depends_on:
      - db
    volumes:
      - .:/var/www/html
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init-multi-db.sql:/docker-entrypoint-initdb.d/init-multi-db.sql
    networks:
      - net
    ports:
      - "3306:3306"

networks:
  net:
    driver: bridge

volumes:
  db_data:
