services:
  app:
    build:
      context: ./app
    ports:
      - 80:80
      - 5173:5173
    networks:
      - net
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
  site:
    build:
      context: ./site
    ports:
      - 8080:80
    networks:
      - net
    depends_on:
      - db
    volumes:
      - ./site:/var/www/html
    environment:
      DB_HOST: ${WP_DB_HOST}
      DB_NAME: ${WP_DB_NAME}
      DB_PASSWORD: ${WP_DB_PASSWORD}
      DB_USER: ${WP_DB_USER}
      AUTH_KEY: ${WP_AUTH_KEY}
      AUTH_SALT: ${WP_AUTH_SALT}
      LOGGED_IN_KEY: ${WP_LOGGED_IN_KEY}
      LOGGED_IN_SALT: ${WP_LOGGED_IN_SALT}
      NONCE_KEY: ${WP_NONCE_KEY}
      NONCE_SALT: ${WP_NONCE_SALT}
      SECURE_AUTH_KEY: ${WP_SECURE_AUTH_KEY}
      SECURE_AUTH_SALT: ${WP_SECURE_AUTH_SALT}
      WP_HOME: http://localhost:8080 
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init-multi-db.sql:/docker-entrypoint-initdb.d/init-multi-db.sql
    networks:
      - net
    ports:
      - "3306:3306"

networks:
  net:
    driver: bridge

volumes:
  db_data:
