name: site build

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: site:latest
      env:
        WP_DB_HOST: ${{ secrets.WP_DB_HOST }}
        WP_DB_NAME: ${{ secrets.WP_DB_NAME }}
        WP_DB_PASSWORD: ${{ secrets.WP_DB_PASSWORD }}
        WP_DB_USER: ${{ secrets.WP_DB_USER }}
        WP_AUTH_KEY: ${{ secrets.WP_AUTH_KEY }}
        WP_AUTH_SALT: ${{ secrets.WP_AUTH_SALT }}
        WP_LOGGED_IN_KEY: ${{ secrets.WP_LOGGED_IN_KEY }}
        WP_LOGGED_IN_SALT: ${{ secrets.WP_LOGGED_IN_SALT }}
        WP_NONCE_KEY: ${{ secrets.WP_NONCE_KEY }}
        WP_NONCE_SALT: ${{ secrets.WP_NONCE_SALT }}
        WP_SECURE_AUTH_KEY: ${{ secrets.WP_SECURE_AUTH_KEY }}
        WP_SECURE_AUTH_SALT: ${{ secrets.WP_SECURE_AUTH_SALT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: us-east-1

      - name: Build and push Docker image
        run: |
          docker build -t site:latest -f site/Dockerfile site 
          docker tag site:latest ${{secrets.LOCATION}}/site:latest
          docker push ${{secrets.LOCATION}}/site:latest
